Вы разрабатываете приложение для прослушивания музыки. Конечно же, там будет доступна функция перемешивания плейлиста. Пользователю может настолько понравиться перемешанная версия плейлиста, что он захочет сохранить его копию. Однако вы не хотите хранить в памяти новую версию плейлиста, а просто хотите сохранять тот seed, с которым он был сгенерирован.

Для этого напишите функцию shuffle_seed(array), которая принимает на вход массив из чисел, генерирует случайное число для seed в диапазоне от 0 до 2**32 - 1 (включительно) и возвращает кортеж: перемешанный с данным seed массив (исходный массив должен оставаться без изменений), а также seed, с которым этот массив был получен.

1. генерация случайного сид в пределах
2. при новом сиде делаем шафл плейлиста с сохранением в новую переменную.
3. выводим новый плейлист и сид в виде кортежа

In [8]:
import numpy as np

def shuffle_seed(array):
    # генерим случайный сид
    seed = np.random.randint(0, 2**32, dtype = np.int64)
    #задаем рандом при сгенерированном сиде
    np.random.seed(seed)
    #перемешиваем массив и сохраняем его в новую переменную
    shuffled = np.random.permutation(array)
    #возвращаем в нужном формате
    return (shuffled, seed)
array = [1, 2, 3, 4, 5]
shuffle_seed(array)

(array([5, 3, 4, 1, 2]), np.int64(1164908330))

Напишите функцию min_max_dist(*vectors), которая принимает на вход неограниченное число векторов через запятую. Гарантируется, что все векторы, которые передаются, одинаковой длины.

Функция возвращает минимальное и максимальное расстояние между векторами в виде кортежа.

Пример


vec1 = np.array([1,2,3])
vec2 = np.array([4,5,6])
vec3 = np.array([7, 8, 9])

min_max_dist(vec1, vec2, vec3)

 (5.196152422706632, 10.392304845413264)

1. цикл по всем векторам
2. находим расстояние между ними и записываем в список
3. выводим результат в виде кортежа (мин,макс)

In [26]:
import numpy as np
from collections import deque

def min_max_dist(*vectors):
    vectors_dq = deque(vectors)
    distance_list = []
    while len(vectors_dq) > 1: 
        for i in range(len(vectors_dq)-1):      
            distance = np.linalg.norm(vectors_dq[0] - vectors_dq[i+1])
            distance_list.append(distance)            
        del vectors_dq[0]

    result = (min(distance_list), max(distance_list))
    return result
vec1 = np.array([1,2,3])
vec2 = np.array([4,5,6])
vec3 = np.array([7, 8, 9])

min_max_dist(vec1, vec2, vec3)
# (5.196152422706632, 10.392304845413264)

(np.float64(5.196152422706632), np.float64(10.392304845413264))

Напишите функцию any_normal, которая принимает на вход неограниченное число векторов через запятую. Гарантируется, что все векторы, которые передаются, одинаковой длины.

Функция возвращает True, если есть хотя бы одна пара перпендикулярных векторов. Иначе возвращает False.

In [29]:
import numpy as np
from collections import deque

def any_normal(*vec):
    vec_dq = deque(vec)
    scalar_list = []
    while len(vec_dq) > 1: 
        for i in range(len(vec_dq)-1):      
            scalar_product = np.dot(vec[0], vec[i+1])
            scalar_list.append(scalar_product)            
        del vec_dq[0] 
    print(scalar_list)    
    for elem in scalar_list:
        if elem != 0:
            return False
        else:
            return True  
vec1 = np.array([2, 1])
vec2 = np.array([-1, 2])
vec3 = np.array([3,4])
print(any_normal(vec1, vec2, vec3))

[np.int64(0), np.int64(10), np.int64(0)]
True


Напишите функцию get_loto(num), генерирующую трёхмерный массив случайных целых чисел от 1 до 100 (включительно). Это поля для игры в лото.

Трёхмерный массив должен состоять из таблиц чисел формы 5х5, то есть итоговая форма — (num, 5, 5).

Функция возвращает полученный массив.

In [30]:
import numpy as np
def get_loto(num):
    res = np.random.choice(np.arange(1, 101), size=(num,5,5), replace=False)
    return res
get_loto(3)

array([[[88, 16, 47,  1, 31],
        [60, 72, 12, 53,  9],
        [49,  3, 35, 34, 94],
        [70, 96, 71, 17, 28],
        [44,  7, 79, 95, 29]],

       [[69, 25, 99, 73, 67],
        [10, 87, 18, 98, 13],
        [48,  8, 90, 83, 42],
        [56,  6, 65, 85, 68],
        [19, 93, 23, 14, 92]],

       [[43, 24, 80, 30,  2],
        [74, 66, 52, 82, 27],
        [50, 20, 41, 39, 63],
        [86, 45, 97, 26, 38],
        [54, 36, 59, 62, 84]]])

Напишите функцию get_unique_loto(num). Она так же, как и функция в задании 49.9.10, генерирует num полей для игры в лото, однако теперь на каждом поле 5х5 числа не могут повторяться.

Функция также должна возвращать массив формы num x 5 x 5.

Пример

get_unique_loto(3)

In [45]:
import numpy as np

def get_unique_loto(num):
    sample = np.arange(1, 101)
    res = list()
    for i in range(num):
        res.append(np.random.choice(sample, replace=False, size=(5, 5)))
    res = np.array(res)
    return res
get_unique_loto(3)

array([[[ 18,  77,  13,  62,   6],
        [ 51,  55,   9,   8,  82],
        [ 97,  21,  93,   1,  35],
        [ 27,  24,  25,  85,  92],
        [ 33,   2,  63,  78,  49]],

       [[ 79,   8,  56,  82,  37],
        [ 10,  35,  29,  86,  44],
        [ 24,  55,  49, 100,  87],
        [ 90,  70,  95,  67,  83],
        [ 53,  89,  30,  84,  14]],

       [[  6,  45,  18,  69,  73],
        [  4,  11,  47,  22,  60],
        [ 21,  27,  17,  52,  46],
        [ 63,   5,   2,  48,  96],
        [ 24,  89,  35,  62,  10]]])