## Случайные числа

Генерация float

In [1]:
import numpy as np
np.random.rand()

0.33289054255368666

Чтобы получить случайное число в диапазоне, например, от 0 до 100, достаточно просто умножить генерируемое число на 100:

In [2]:
np.random.rand() * 100

82.83873421831818

На самом деле rand умеет генерировать не только отдельные числа — функция принимает в качестве аргументов через запятую целые числа, которые задают форму генерируемого массива. Например, получим массив из пяти случайных чисел:

In [4]:
np.random.rand(5)

array([0.67442955, 0.85365628, 0.79898861, 0.46664906, 0.61401622])

In [3]:
np.random.rand(2, 3)

array([[0.07750111, 0.02512296, 0.07908807],
       [0.56322619, 0.35497704, 0.36939848]])

Если передать в rand кортеж, возникнет ошибка:

In [5]:
shape = (3, 4)
np.random.rand(shape)

TypeError: 'tuple' object cannot be interpreted as an integer

In [6]:
shape = (3, 4)
np.random.rand(*shape)

array([[0.92664144, 0.73200002, 0.13060008, 0.25645734],
       [0.68685962, 0.73499111, 0.30830287, 0.1933339 ],
       [0.80937757, 0.70426278, 0.65593378, 0.00274376]])

Но в NumPy есть и другая функция, генерирующая массивы случайных чисел от 0 до 1, которая принимает в качестве аргумента именно кортеж без распаковки. Она называется sample:

In [7]:
shape = (2, 3)
np.random.sample(shape)

array([[0.30610312, 0.79178928, 0.55392397],
       [0.44183492, 0.48890012, 0.81381746]])

Не всегда требуются числа в диапазоне именно от 0 до 1. На самом деле с помощью специальных формул можно из диапазона от 0 до 1 получить любой другой желаемый диапазон, однако это не требуется делать самостоятельно — в NumPy доступна функция uniform:

uniform(low=0.0, high=1.0, size=None)

Запуск без аргументов эквивалентен работе функций rand или sample:

In [9]:
np.random.uniform()

0.5048870953765107

In [10]:
np.random.uniform(-30, 50)

-16.681610379906058

Получим пять чисел в интервале от 0.5 до 0.75:

In [11]:
np.random.uniform(0.5, 0.75, size=5)

array([0.56999328, 0.60617952, 0.65740911, 0.65561791, 0.66331123])

In [12]:
np.random.uniform(-1000, 500, size=(2, 3))

array([[-897.05225714,  497.22206216, -877.01801718],
       [ 240.35872282,  134.50584633, -180.87601498]])

Генерация int

Не всегда требуется генерировать числа с плавающей точкой. Иногда бывает удобно получить целые числа int (например, для поля игры в лото). Для генерации целых чисел используется функция random.randint:

randint(low, high=None, size=None, dtype=int)

Функцию randint нельзя запустить совсем без параметров, необходимо указать хотя бы одно число.

Если указан только аргумент low, числа будут генерироваться от 0 до low-1, то есть верхняя граница не включается.
Если задать low и high, числа будут генерироваться от low (включительно) до high (не включительно).
size задаёт форму массива уже привычным для вас образом: одним числом — для одномерного или кортежем — для многомерного.
dtype позволяет задать конкретный тип данных, который должен быть использован в массиве.

In [13]:
np.random.randint(4, size=(2,3))

array([[1, 3, 2],
       [1, 0, 3]], dtype=int32)

In [14]:
np.random.randint(6, 12, size=(3,3))

array([[11, 10,  9],
       [ 9,  9, 10],
       [10,  6,  7]], dtype=int32)

### Генерация выборок

Просто перемешать все числа в массиве позволяет функция random.shuffle.

In [15]:
arr = np.arange(6)
print(arr)

[0 1 2 3 4 5]


In [18]:
print(np.random.shuffle(arr))
# None
arr

None


array([4, 0, 1, 2, 3, 5])

Чтобы получить новый перемешанный массив, а исходный оставить без изменений, можно использовать функцию random.permutation. Она принимает на вход один аргумент — или массив целиком, или одно число:

In [22]:
playlist = ["The Beatles", "Pink Floyd", "ACDC", "Deep Purple"]
shuffled = np.random.permutation(playlist)
print(shuffled)

['Deep Purple' 'The Beatles' 'Pink Floyd' 'ACDC']


In [20]:
print(playlist)

['The Beatles', 'Pink Floyd', 'ACDC', 'Deep Purple']


Обратите внимание, что необязательно передавать в функцию сразу массив: в этот раз мы передали в качестве аргумента список и ошибки не возникло. При этом на выходе получился уже NumPy-массив (это заметно по отсутствию запятых при печати массива). Сам список playlist при этом остался без изменений.

Перемешать набор чисел от 0 до n-1 можно с помощью записи np.random.permutation(n), где n — верхняя граница, которая бы использовалась для генерации набора чисел функцией arange.

In [23]:
np.random.permutation(10)

array([8, 0, 3, 5, 2, 7, 9, 4, 1, 6], dtype=int32)

Чтобы получить случайный набор объектов из массива, используется функция random.choice:

choice(a, size=None, replace=True)

a — одномерный массив или число для генерации arange(a);
size — желаемая форма массива (число для получения одномерного массива, кортеж — для многомерного; если параметр не задан, возвращается один объект);
replace — параметр, задающий, могут ли элементы повторяться (по умолчанию могут).

Выберем случайным образом из списка двоих человек, которые должны будут выступить с отчётом на этой неделе. Для этого из списка имён (опять же, можно передавать в функцию choice не NumPy-массив, а список) получим два случайных объекта без повторений (логично, что нужно выбрать двух разных людей). Сделать это можно вот так:

In [27]:
workers = ['Ivan', 'Nikita', 'Maria', 'John', 'Kate']
 
choice = np.random.choice(workers, size=2, replace=False)
print(choice)

['Kate' 'Maria']


Выборка с повторениями используется по умолчанию. Она применяется в том случае, когда мы допускаем, что объекты могут повторяться.

Например, получим случайную последовательность, которая образуется в результате десяти подбрасываний игральной кости:

In [29]:
choice = np.random.choice([1,2,3,4,5,6], size=10)
print(choice)

[1 3 1 2 2 5 5 6 6 6]


сгенерировать десять случайных чисел в диапазоне от 1 до 20 (включительно), которые гарантированно не будут повторяться

In [30]:
np.random.choice(np.arange(1, 21), size=10, replace=False)

array([16,  6, 19, 10, 20,  7, 17, 11, 15,  3])

Seed генератора псевдослучайных чисел

Самостоятельно задать seed в NumPy можно с помощью функции np.random.seed(<np.uint32>). Число в скобках должно быть в пределах от 0 до 2**32 - 1 (=4294967295).

In [34]:
np.random.seed(23)
np.random.randint(10, size=(3,4))

array([[3, 6, 8, 9],
       [6, 8, 7, 9],
       [3, 6, 1, 2]], dtype=int32)

In [33]:
np.random.seed(100)
print(np.random.randint(10, size=3))

[8 8 3]


In [35]:
print(np.random.randint(10, size=3))

[5 5 0]
