Операции с векторами

Операция, применённая к двум векторам, на самом деле применяется поэлементно. То есть при сложении двух векторов первым элементом нового вектора будет сумма первых элементов исходных векторов, вторым — сумма вторых элементов и т. д.

In [1]:
import numpy as np
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])
vec1 + vec2

array([14. , 10. , 10.6, 15.5])

Что бы произошло при сложении двух списков? Их элементы просто объединились бы в один список:

In [2]:
list1 = [2, 4, 7, 2.5]
list2 = [12, 6, 3.6, 13]
list1 + list2

[2, 4, 7, 2.5, 12, 6, 3.6, 13]

In [3]:
[x + y for x, y in zip(list1, list2)]

[14, 10, 10.6, 15.5]

** Для совершения арифметических операций с векторами они должны быть одинаковой длины **

In [4]:
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])
vec1 * vec2

array([24. , 24. , 25.2, 32.5])

вектор целиком можно умножить на число или возвести в степень этого числа:

In [5]:
vec = np.arange(5)
vec * 10

array([ 0, 10, 20, 30, 40])

In [6]:
vec ** 2

array([ 0,  1,  4,  9, 16])

Также векторы можно сравнивать друг с другом поэлементно:

In [7]:
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])
 
vec1 > vec2

array([False, False,  True, False])

Аналогично можно сравнивать вектор с числом:

In [8]:
vec = np.array([14,15,9,26,53,5,89])
vec <= 26

array([ True,  True,  True,  True, False,  True, False])

Длина вектора (норма)

In [9]:
vec = np.array([3, 4])

In [10]:
length = np.sqrt(np.sum(vec ** 2))
print(length)

5.0


Но можно было поступить проще. В NumPy есть специальный подмодуль linalg, который позволяет производить операции из линейной алгебры.

Для вычисления длины вектора нам потребуется функция norm:

In [11]:
length = np.linalg.norm(vec)
print(length)

5.0


РАССТОЯНИЕ

Расстояние между двумя векторами, то есть расстояние между их концами, [в евклидовом пространстве] вычисляется как квадратный корень из суммы квадратов разностей соответствующих координат.

По сути, расстояние между векторами — это длина такого вектора, который является разностью этих векторов. В самом деле, при вычитании двух векторов вычитаются их соответствующие координаты.

In [12]:
vec1 = np.array([0, 3, 5])
vec2 = np.array([12, 4, 7])
distance = np.sqrt(np.sum((vec1 - vec2) ** 2))
distance

np.float64(12.206555615733702)

In [13]:
vec1 = np.array([0, 3, 5])
vec2 = np.array([12, 4, 7])
distance = np.linalg.norm(vec1 - vec2)
distance

np.float64(12.206555615733702)

СКАЛЯРНОЕ ПРОИЗВЕДЕНИЕ

скалярным произведением двух векторов называют сумму произведений их соответствующих координат.

In [14]:
vec1 = np.arange(1, 6)
vec2 = np.linspace(10, 20, 5)
scalar_product = np.sum(vec1 * vec2)
scalar_product

np.float64(250.0)

In [15]:
scalar_product = np.dot(vec1, vec2)
scalar_product

np.float64(250.0)

Скалярное произведение также имеет широкое применение в математике и других операциях с векторами. В частности, равенство скалярного произведения нулю означает перпендикулярность рассматриваемых векторов:

In [16]:
x = np.array([25, 0])
y = np.array([0, 10])
np.dot(x, y)

np.int64(0)

Векторы в геометрии называются сонаправленными, если они коллинеарны и их направления совпадают. Отметим, что прямые, на которых лежат сонаправленные вектора, всегда по определению являются параллельными.

есть несколько математических способов определить сонаправленность векторов. Один из них: сумма длин сонаправленных векторов должна быть равной длине суммы двух векторов.

## Базовые статистические функции для векторов

Функции np.min и np.max позволяют находить максимальное и минимальное значение в векторе. Их можно записывать как в виде np.min(<vector>), так и в виде <vector>.min():

In [17]:
vec = np.array([2,7,18,28,18,1,8,4])
vec.min()

np.int64(1)

In [18]:
np.max(vec)

np.int64(28)

Функция mean позволяет посчитать среднее значение. Больше не требуется реализовывать её «руками»!

In [19]:
vec.mean()

np.float64(10.75)

Диапазон значений (максимум — минимум) по оси. - ptp(a[, axis, out, keepdims])

Вычислите q-й процентиль данных по указанной оси. - percentile(a, q[, axis, out, ...])

Вычислите q-й процентиль данных по указанной оси, игнорируя значения NaN. - nanpercentile(a, q[, axis, out, ...])

Вычислите q-й квантиль данных по указанной оси. - quantile(a, q[, axis, out, overwrite_input, ...])

Вычислите q-й квантиль данных по указанной оси, игнорируя значения NaN. - nanquantile(a, q[, axis, out, ...])

Вычислите медиану по указанной оси. - 
median(a[, axis, out, overwrite_input, keepdims])

Вычислите средневзвешенное значение по указанной оси.
average(a[, axis, weights, returned, keepdims])

Вычислите среднее арифметическое по указанной оси.
mean(a[, axis, dtype, out, keepdims, where])

Вычислите стандартное отклонение по указанной оси.
std(a[, axis, dtype, out, ddof, keepdims, ...])

Вычислите дисперсию по указанной оси.
var(a[, axis, dtype, out, ddof, keepdims, ...])

Вычислите медиану по указанной оси, игнорируя значения NaN.
nanmedian(a[, axis, out, overwrite_input, ...])

Вычислите среднее арифметическое по указанной оси, игнорируя значения NaN.
nanmean(a[, axis, dtype, out, keepdims, where])

Вычислите стандартное отклонение по указанной оси, игнорируя значения NaN.
nanstd(a[, axis, dtype, out, ddof, ...])

Вычислите дисперсию по указанной оси, игнорируя значения NaN.
nanvar(a[, axis, dtype, out, ddof, ...])