## Случайные числа

Генерация float

In [1]:
import numpy as np
np.random.rand()

0.629573195691572

Чтобы получить случайное число в диапазоне, например, от 0 до 100, достаточно просто умножить генерируемое число на 100:

In [2]:
np.random.rand() * 100

54.28171920792187

На самом деле rand умеет генерировать не только отдельные числа — функция принимает в качестве аргументов через запятую целые числа, которые задают форму генерируемого массива. Например, получим массив из пяти случайных чисел:

In [3]:
np.random.rand(5)

array([0.23508394, 0.99136187, 0.22929543, 0.47438273, 0.71245762])

In [4]:
np.random.rand(2, 3)

array([[0.35956704, 0.62646928, 0.71126712],
       [0.74832971, 0.66577947, 0.9605157 ]])

Если передать в rand кортеж, возникнет ошибка:

In [5]:
shape = (3, 4)
np.random.rand(shape)

TypeError: 'tuple' object cannot be interpreted as an integer

In [5]:
shape = (3, 4)
np.random.rand(*shape)

array([[0.49733012, 0.17956934, 0.0349044 , 0.74302111],
       [0.73597014, 0.86305867, 0.43713812, 0.75325302],
       [0.72178254, 0.36857769, 0.58194003, 0.05775524]])

Но в NumPy есть и другая функция, генерирующая массивы случайных чисел от 0 до 1, которая принимает в качестве аргумента именно кортеж без распаковки. Она называется sample:

In [6]:
shape = (2, 3)
np.random.sample(shape)

array([[0.38599158, 0.24865019, 0.47716162],
       [0.66576211, 0.62904939, 0.66886197]])

Не всегда требуются числа в диапазоне именно от 0 до 1. На самом деле с помощью специальных формул можно из диапазона от 0 до 1 получить любой другой желаемый диапазон, однако это не требуется делать самостоятельно — в NumPy доступна функция uniform:

```python
uniform(low=0.0, high=1.0, size=None)

Запуск без аргументов эквивалентен работе функций rand или sample:

In [7]:
np.random.uniform()

0.7370339851404536

In [9]:
np.random.uniform(-30, 50)

-2.570526399856064

Получим пять чисел в интервале от 0.5 до 0.75:

In [10]:
np.random.uniform(0.5, 0.75, size=5)

array([0.510343  , 0.66208141, 0.59716878, 0.70349528, 0.51348718])

In [11]:
np.random.uniform(-1000, 500, size=(2, 3))

array([[ -24.7715476 , -901.02519942, -274.1788708 ],
       [ 376.38211149,  455.50174376, -927.49001278]])

## Генерация int

Не всегда требуется генерировать числа с плавающей точкой. Иногда бывает удобно получить целые числа int (например, для поля игры в лото). Для генерации целых чисел используется функция random.randint:
```python
randint(low, high=None, size=None, dtype=int)

Функцию randint нельзя запустить совсем без параметров, необходимо указать хотя бы одно число.

Если указан только аргумент low, числа будут генерироваться от 0 до low-1, то есть верхняя граница не включается.
Если задать low и high, числа будут генерироваться от low (включительно) до high (не включительно).
size задаёт форму массива уже привычным для вас образом: одним числом — для одномерного или кортежем — для многомерного.
dtype позволяет задать конкретный тип данных, который должен быть использован в массиве.

In [12]:
np.random.randint(4, size=(2,3))

array([[1, 2, 0],
       [1, 0, 2]])

In [13]:
np.random.randint(6, 12, size=(3,3))

array([[ 8,  8,  8],
       [ 7,  9, 11],
       [ 9,  9,  8]])

### Генерация выборок

>Просто перемешать все числа в массиве позволяет функция random.shuffle.

In [17]:
arr = np.arange(6)
print(arr)

[0 1 2 3 4 5]


In [15]:
print(np.random.shuffle(arr))
# None
arr

None


array([3, 5, 0, 1, 2, 4])

>Чтобы получить новый перемешанный массив, а исходный оставить без изменений, можно использовать функцию random.permutation. 
Она принимает на вход один аргумент — или массив целиком, или одно число:

In [16]:
playlist = ["The Beatles", "Pink Floyd", "ACDC", "Deep Purple"]
shuffled = np.random.permutation(playlist)
print(shuffled)

['Pink Floyd' 'ACDC' 'The Beatles' 'Deep Purple']


In [20]:
print(playlist)

['The Beatles', 'Pink Floyd', 'ACDC', 'Deep Purple']


Обратите внимание, что необязательно передавать в функцию сразу массив: в этот раз мы передали в качестве аргумента список и ошибки не возникло. При этом на выходе получился уже NumPy-массив (это заметно по отсутствию запятых при печати массива). Сам список playlist при этом остался без изменений.

Перемешать набор чисел от 0 до n-1 можно с помощью записи np.random.permutation(n), где n — верхняя граница, которая бы использовалась для генерации набора чисел функцией arange.

In [22]:
np.random.permutation(10)

array([1, 9, 3, 7, 4, 8, 5, 6, 0, 2])

>Чтобы получить случайный набор объектов из массива, используется функция random.choice:

choice(a, size=None, replace=True)

a — одномерный массив или число для генерации arange(a);
size — желаемая форма массива (число для получения одномерного массива, кортеж — для многомерного; если параметр не задан, возвращается один объект);
replace — параметр, задающий, могут ли элементы повторяться (по умолчанию могут).

Выберем случайным образом из списка двоих человек, которые должны будут выступить с отчётом на этой неделе. Для этого из списка имён (опять же, можно передавать в функцию choice не NumPy-массив, а список) получим два случайных объекта без повторений (логично, что нужно выбрать двух разных людей). Сделать это можно вот так:

In [29]:
workers = ['Ivan', 'Nikita', 'Maria', 'John', 'Kate']
 
choice = np.random.choice(workers, size=2, replace=False)
print(choice)

['John' 'Maria']


Выборка с повторениями используется по умолчанию. Она применяется в том случае, когда мы допускаем, что объекты могут повторяться.

Например, получим случайную последовательность, которая образуется в результате десяти подбрасываний игральной кости:

In [33]:
choice = np.random.choice([1,2,3,4,5,6], size=10)
print(choice)

[4 5 5 5 4 5 6 2 6 4]


сгенерировать десять случайных чисел в диапазоне от 1 до 20 (включительно), которые гарантированно не будут повторяться

In [35]:
np.random.choice(np.arange(1, 21), size=10, replace=False)

array([15,  1, 14, 17, 11,  8,  2, 12, 16,  6])

## Seed генератора псевдослучайных чисел

Самостоятельно задать seed в NumPy можно с помощью функции np.random.seed(<np.uint32>). Число в скобках должно быть в пределах от 0 до 2**32 - 1 (=4294967295).

In [37]:
np.random.seed(23)
np.random.randint(10, size=(3,4))

array([[3, 6, 8, 9],
       [6, 8, 7, 9],
       [3, 6, 1, 2]])

In [38]:
np.random.seed(100)
print(np.random.randint(10, size=3))

[8 8 3]


In [39]:
print(np.random.randint(10, size=3))

[7 7 0]
