# Массив

Создание

In [3]:
import numpy as np
arr = np.array([1,5,2,9,10])
arr

array([ 1,  5,  2,  9, 10])

In [4]:
print(type(arr))

<class 'numpy.ndarray'>


In [5]:
# Перечислить список из списков можно
# было и в одну строку, но на нескольких
# строках получается нагляднее
nd_arr = np.array([
               [12, 45, 78],
               [34, 56, 13],
               [12, 98, 76]
               ])
nd_arr

array([[12, 45, 78],
       [34, 56, 13],
       [12, 98, 76]])

Типы данных в массиве

In [6]:
arr = np.array([1,5,2,9,10])
arr.dtype

dtype('int64')

In [7]:
arr = np.array([1,5,2,9,10], dtype=np.int8)
arr

array([ 1,  5,  2,  9, 10], dtype=int8)

In [8]:
arr[2] = 2000
arr

OverflowError: Python integer 2000 out of bounds for int8

In [9]:
arr = np.array([1,5,2,9,10], dtype=np.int8)
arr[2] = 125.5
arr

array([  1,   5, 125,   9,  10], dtype=int8)

In [10]:
arr[2] = '12'
arr

array([ 1,  5, 12,  9, 10], dtype=int8)

Поменять тип данных во всём массиве можно с помощью тех же функций, которыми мы пользовались для преобразования типов отдельных переменных в предыдущем юните (например, np.int32 или np.float64):

In [13]:
arr = np.array([1,5,2,9,10], dtype=np.int8)
arr = np.float64(arr)
arr

array([ 1.,  5.,  2.,  9., 10.])

In [16]:
arr = np.array([12321, -1234, 3435, -214, 100], dtype=np.int32)
arr


array([12321, -1234,  3435,  -214,   100], dtype=int32)

In [17]:
arr = np.uint8(arr)
arr

array([ 33,  46, 107,  42, 100], dtype=uint8)

Свойства NumPy-массивов

In [18]:
arr = np.array([1,5,2,9,10], dtype=np.int8)
nd_arr = np.array([
               [12, 45, 78],
               [34, 56, 13],
               [12, 98, 76]
               ], dtype=np.int16)

Узнать размерность массива можно с помощью .ndim:

In [20]:
arr.ndim
# 1


1

In [21]:
nd_arr.ndim
# 2

2

Узнать общее число элементов в массиве можно с помощью .size:

In [22]:
arr.size

5

In [23]:
nd_arr.size

9

Форма или структура массива хранится в атрибуте .shape:

In [24]:
arr.shape

(5,)

In [26]:
nd_arr.shape

(3, 3)

Наконец, узнать, сколько «весит» каждый элемент массива в байтах позволяет .itemsize:

In [27]:
arr.itemsize

1

In [28]:
nd_arr.itemsize

2

Заполнение новых массивов

Можно заранее подготовить массив заданной размерности, заполненный нулями, а потом загружать в него реальные данные по мере необходимости.

Массив из нулей создаётся функцией np.zeros. Она принимает аргументы shape (обязательный) — форма массива (одно число или кортеж) и dtype (необязательный) — тип данных, который будет храниться в массиве.

In [29]:
zeros_1d = np.zeros(5)
zeros_1d

array([0., 0., 0., 0., 0.])

In [30]:
zeros_3d = np.zeros((5,4,3), dtype=np.float32)
print(zeros_3d.shape)

(5, 4, 3)


Ещё одной удобной функцией для создания одномерных массивов является arange. Она аналогична встроенной функции range, но обладает рядом особенностей. Вот её сигнатура: arange([start,] stop, [step,], dtype=None).

Аргументы start (по умолчанию 0), step (по умолчанию 1) и dtype (определяется автоматически) являются необязательными:

start (входит в диапазон возвращаемых значений) задаёт начальное число;
stop (не входит в диапазон возвращаемых значений, как и при использовании range) задаёт правую границу диапазона;
step задаёт шаг, с которым в массив добавляются новые значения.
В отличие от range, в функции arange все перечисленные параметры могут иметь тип float.

In [31]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [32]:
np.arange(2.5, 5)

array([2.5, 3.5, 4.5])

Создадим массив от 2.5 до 5 с шагом 0.5:

In [33]:
np.arange(2.5, 5, 0.5)

array([2.5, 3. , 3.5, 4. , 4.5])

In [34]:
np.arange(2.5, 5, 0.5, dtype=np.float16)

array([2.5, 3. , 3.5, 4. , 4.5], dtype=float16)

На самом деле операции с плавающей точкой не всегда бывают предсказуемыми из-за особенностей хранения таких чисел в памяти компьютера. Поэтому для работы с дробными параметрами start, stop и step лучше использовать функцию # linspace (англ. linear space — линейное пространство). Она тоже возвращает одномерный массив из чисел, расположенных на равном удалении друг от друга между началом и концом диапазона, но обладает немного другим поведением и сигнатурой:

np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)

start и stop являются обязательными параметрами, задающими начало и конец возвращаемого диапазона;
num — параметр, задающий число элементов, которое должно оказаться в массиве (по умолчанию 50);
endpoint — включён или исключён конец диапазона (по умолчанию включён);
retstep (по умолчанию False) позволяет указать, возвращать ли использованный шаг между значениями, помимо самого массива;
dtype — уже хорошо знакомый нам параметр, задающий тип данных (если не задан, определяется автоматически).

In [37]:
arr = np.linspace(1, 2, 8)
arr


array([1.        , 1.14285714, 1.28571429, 1.42857143, 1.57142857,
       1.71428571, 1.85714286, 2.        ])

Создадим массив из десяти чисел между 1 и 2, не включая 2:

In [38]:
arr = np.linspace(1, 2, 10, endpoint=False)
arr

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

Узнаем, какой шаг был использован для создания массива из десяти чисел между 1 и 2, где 2 включалось и не включалось:

In [39]:
arr, step = np.linspace(1, 2, 10, endpoint=True, retstep=True)
print(step)

0.1111111111111111


In [40]:
arr, step = np.linspace(1, 2, 10, endpoint=False, retstep=True)
print(step)

0.1


In [41]:
arr, step = np.linspace(-6, 21, 60, endpoint=False, retstep=True)
print(step)

0.45


Изменение формы массива

In [42]:
import numpy as np
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

Поменять форму массива arr можно с помощью присвоения атрибуту shape кортежа с желаемой формой:

In [48]:
arr.shape = (2 ,4)
arr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

Присвоение нового значения атрибуту shape изменяет тот массив, с которым производится действие.

Чтобы оставить исходный массив без изменений и дополнительно получить новый массив новой формы, нужно использовать функцию reshape. Она также принимает в качестве аргумента кортеж из чисел для формы, но возвращает новый массив, а не изменяет исходный:

In [50]:
arr = np.arange(8)
arr_new = arr.reshape((2,4))
arr_new

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

У функции reshape есть дополнительный именованный аргумент order. Он задаёт принцип, по которому элементы заполняют массив новой формы. Если order='C' (по умолчанию), массив заполняется по строкам, как в примере выше. Если order='F', массив заполняется числами по столбцам:

In [51]:
arr = np.arange(8)
arr_new = arr.reshape((2, 4), order='F')
arr_new

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

транспонирование

In [55]:
arr = np.arange(8)
arr.shape = (2, 4)
arr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [56]:
arr_transe = arr.transpose()
arr_transe

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

Индексы и срезы в массивах

In [59]:
arr = np.linspace(1, 2, 6)
arr

array([1. , 1.2, 1.4, 1.6, 1.8, 2. ])

In [60]:
print(arr[2])

1.4


In [61]:
print(arr[2:4])

[1.4 1.6]


In [62]:
print(arr[::-1])

[2.  1.8 1.6 1.4 1.2 1. ]


In [66]:
nd_array = np.linspace(0,6,12,endpoint = False).reshape(3, 4)
nd_array

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5]])

Можно воспользоваться привычной записью нескольких индексов в нескольких квадратных скобках

In [68]:
print(nd_array[1][2])

3.0


In [70]:
print(nd_array[1,2])

3.0


In [75]:
nd_array = np.linspace(0,6,12,endpoint = False).reshape(3, 4)
print(nd_array)
print(nd_array[:2,1])

[[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]
 [4.  4.5 5.  5.5]]
[0.5 2.5]


In [85]:
nd_array = np.linspace(0,6,12,endpoint = False).reshape(3, 4)
print(nd_array)
print()
print(nd_array[:, 2:4])

[[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]
 [4.  4.5 5.  5.5]]

[[1.  1.5]
 [3.  3.5]
 [5.  5.5]]


Напишите функцию get_chess(a), которая принимает на вход длину стороны квадрата a и возвращает двумерный массив формы (a, a), заполненный 0 и 1 в шахматном порядке. В левом верхнем углу всегда должен быть ноль.

Примечание. воспользуйтесь функцией np.zeros, а затем с помощью срезов без циклов задайте необходимым элементам значение 1.

В Python для получения каждого второго элемента используется срез [::2]. Подумайте, как грамотно применить этот принцип к двумерному массиву.

In [152]:
import numpy as np

def get_chess(a):
    arr = np.zeros((a,a))
    arr[1::2, ::2] = 1
    arr[::2, 1::2] = 1
    return arr
    
print(get_chess(4))

[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


Чтобы получить самую последнюю ось (в данном случае все столбцы), двоеточие писать необязательно. Строки будут получены целиком по умолчанию:

In [101]:
nd_array = np.linspace(0,6,12,endpoint = False).reshape(3, 4)
print(nd_array)
print()
print(nd_array[:,2][::-1])

[[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]
 [4.  4.5 5.  5.5]]

[5. 3. 1.]


Вам дан массив mystery

mystery = np.array([[-13586,  15203,  28445, -27117,  -1781, -17182, -18049],
       [ 25936, -30968,  -1297,  -4593,   6451,  15790,   7181],
       [ 13348,  28049,  28655,  -6012,  21762,  25397,   8225],
       [ 13240,   7994,  32592,  20149,  13754,  11795,   -564],
       [-21725,  -8681,  30305,  22260, -17918,  12578,  29943],
       [-16841, -25392, -17278,  11740,   5916,    -47, -32037]],
      dtype=np.int16)
Выполните все пукты задания по порядку.

Пожалуйста, не меняйте названия переменных, в которых должны появиться ответы.

В переменную elem_5_3 сохраните элемент из 5 строки и 3 столбца

В переменную last сохраните элемент из последней строки последнего столбца

В переменную line_4 сохраните строку 4

В переменную col_2 сохраните предпоследний столбец

Из строк 2-4 (включительно) получите столбцы 3-5 (включительно). Результат сохраните в переменную part

Сохраните в переменную rev последний столбец в обратном порядке

Сохраните в переменную trans транспонированный массив

In [ ]:
import numpy as np

mystery = np.array([[-13586,  15203,  28445, -27117,  -1781, -17182, -18049],
       [ 25936, -30968,  -1297,  -4593,   6451,  15790,   7181],
       [ 13348,  28049,  28655,  -6012,  21762,  25397,   8225],
       [ 13240,   7994,  32592,  20149,  13754,  11795,   -564],
       [-21725,  -8681,  30305,  22260, -17918,  12578,  29943],
       [-16841, -25392, -17278,  11740,   5916,    -47, -32037]],
      dtype=np.int16)

elem_5_3 = mystery[4,2]
last = mystery[5,6]
line_4 = mystery[3]
col_2 = mystery[:,5]
part = mystery[1:4,2:5]
rev = mystery[:,6][::-1]
trans = mystery.transpose()

#print(mystery[1:3,2:4])

Сортировка одномерных массивов

Способ 1. Функция np.sort(<массив>) возвращает новый отсортированный массив:

In [102]:
arr = np.array([23,12,45,12,23,4,15,3])
arr_new = np.sort(arr)
print(arr)

[23 12 45 12 23  4 15  3]


In [103]:
print(arr_new)

[ 3  4 12 12 15 23 23 45]


Способ 2. Функция <массив>.sort() сортирует исходный массив и возвращает None:

In [104]:
arr = np.array([23,12,45,12,23,4,15,3])
print(arr.sort())

None


In [105]:
print(arr)

[ 3  4 12 12 15 23 23 45]


Работа с пропущенными данными

In [107]:
data = np.array([4, 9, -4, 3])
roots = np.sqrt(data) #Воспользуемся встроенной в NumPy функцией sqrt, чтобы посчитать квадратные корни из элементов.
roots

C:\Users\1\AppData\Local\Temp\ipykernel_8344\3612371969.py:2: RuntimeWarning: invalid value encountered in sqrt
  roots = np.sqrt(data)


array([2.        , 3.        ,        nan, 1.73205081])

In [108]:
print(type(None))

<class 'NoneType'>


In [109]:
print(type(np.nan))

<class 'float'>


In [110]:
print(None == None)

True


In [111]:
print(np.nan == np.nan)

False


In [112]:
print(np.nan is np.nan)

True


In [113]:
print(np.nan is None)

False


In [114]:
sum(roots)

np.float64(nan)

Можно заполнить пропущенные значения, например, нулями. Для этого с помощью функции np.isnan(<массив>) узнаем, на каких местах в массиве находятся «не числа»:

In [115]:
np.isnan(roots)

array([False, False,  True, False])

In [116]:
roots[np.isnan(roots)]

array([nan])

In [117]:
roots[np.isnan(roots)] = 0
roots

array([2.        , 3.        , 0.        , 1.73205081])

In [119]:
print(sum(roots))

6.732050807568877


Вам дан массив mystery:

mystery = np.array([ 12279., -26024.,  28745.,  np.nan,  31244.,  -2365.,  -6974.,
        -9212., np.nan, -17722.,  16132.,  25933.,  np.nan, -16431.,
        29810.], dtype=np.float32)
Получите булевый массив nans_index с информацией о np.nan в массиве mystery: True - значение пропущено, False - значение не пропущено

В переменную n_nan сохраните число пропущенных значений

Скопируйте массив mystery в массив mystery_new. Заполните пропущенные значения в массиве mystery_new нулями

Поменяйте тип данных в массиве mystery на int32 и сохраните в переменную mystery_int

Отсортируйте значения в массиве mystery по возрастанию и сохраните результат в переменную array

Сохраните в массив table двухмерный массив, полученный из массива array. В нём должно быть 5 строк и 3 столбца. Причём порядок заполнения должен быть по столбцам!

In [121]:
import numpy as np


mystery = np.array([ 12279., -26024.,  28745.,  np.nan,  31244.,  -2365.,  -6974.,
        -9212., np.nan, -17722.,  16132.,  25933.,  np.nan, -16431.,
        29810.], dtype=np.float32)

nans_index = np.isnan(mystery)

count = 0
for elem  in nans_index:
    if elem == True:
        count+=1
n_nan = count

mystery_new = mystery
mystery_new[np.isnan(mystery)] = 0

mystery_int = np.array(mystery_new, dtype=np.int32)

mystery = np.array([ 12279., -26024.,  28745.,  np.nan,  31244.,  -2365.,  -6974.,
        -9212., np.nan, -17722.,  16132.,  25933.,  np.nan, -16431.,
        29810.], dtype=np.float32)

array = np.sort(mystery)

table = array.reshape((5, 3), order='F')

col = table[:,1]
#print(array)
#print(col)